# @package _global_

defaults:
  - _self_
  - data: sampling # choose datamodule with `test_dataloader()` for evaluation
  - model: diffusion
  - logger: null
  - trainer: gpu
  - paths: env
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.data_dir}/last.ckpt
pred_dir: null
